name: 🚀 Deploy Production

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-deploy:
    name: 🎉 Build and Deploy

    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🔨 Set up Node 14.19.1
        uses: actions/setup-node@v2
        with:
          node-version: 14.19.1

      - name: 🛠 Compile Backend
        run: |
          cd server
          npm ci
          npm run build
          cd ..
          mkdir -p deploy/server/dist
          cp -r server/dist deploy/server
          cp server/* deploy/server || :
      - name: ⛏ Build Frontend
        run: |
          cd client
          npm ci
          npm run build
          cd ..
          mkdir -p deploy/public
          cp -r client/build/* deploy/public
        env:
          SERVER_URL: "https://node.rws-hosting.com:4443"

      # - name: ☁ SFTP Deploy
      #   uses: easingthemes/ssh-deploy@v2
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     REMOTE_PORT: 21098
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
      #     SOURCE: ${{ secrets.SOURCE_DIR }}
